# see https://docs.github.com/en/actions/creating-actions/creating-a-composite-action#creating-an-action-metadata-file
name: "Setup Node"
description: "Setup node and install dependencies (with cache)"

inputs:
  node-version:
    description: "What node version to use"
    required: false
    default: "18.x"

runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Download deps
      uses: bahmutov/npm-install@v1
