tasks:
  - name: Start environment
    init: yarn install
    command: yarn dev

#  - name: Open browser
#    command: gp preview $(gp url 3000)docs

ports:
  - port: 3000
    onOpen: open-preview

github:
  prebuilds:
    master: true
