name: Unit Tests for Docs

on: [push]

defaults:
  run:
    working-directory: docs

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          working-directory: openapi
      - name: Run unit tests
        run: yarn test
