name: Unit Tests for Docs

on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: ./.github/actions/setup-node
        with:
          working-directory: docs
      - name: Run unit tests
        run: yarn  --cwd ./docs test
