name: openapi
on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Validate OpenAPI spec
        run: yarn --cwd ./openapi validate

  smoke-test:
    runs-on: ubuntu-latest
    environment: staging
    needs: validate
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Smoke test
        uses: ./.github/actions/smoke-test
        env:
          SERVER_URL: "${{ secrets.MAGICBELL_SERVER_URL }}"
          USER_EMAIL: "${{ secrets.MAGICBELL_USER_EMAIL }}"
          API_KEY: "${{ secrets.MAGICBELL_API_KEY }}"
          API_SECRET: "${{ secrets.MAGICBELL_API_SECRET }}"
