name: Update Postman Collection

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - main

jobs:
  postman:
    name: Postman Collection Update
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'pull_request' && 'Preview' || 'Production' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install curl and jq
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Install openapi-to-postman tool
        run: npm i -g openapi-to-postmanv2

      - name: Convert openapi spec to Postman Spec
        run: "cd openapi/spec && openapi2postmanv2 -s openapi.json -o postman-spec.json -p"

        # The Postman API for updating a collection requires the postman spec to be in a collection object
        # This command uses jq to add the postman spec to a collection object and outputs that to `postman-spec-in-collection-obj.json` file
      - name: Add Postman Spec to a collection object
        run: "cd openapi/spec && cat postman-spec.json | jq '{collection: {item: .item, info: .info}}' > postman-spec-in-collection-obj.json"

      - name: Update the Postman Collection
        run: |
          curl --location --request PUT 'https://api.getpostman.com/collections/${{ vars.POSTMAN_COLLECTION_ID }}' \
          --header 'Content-Type: application/json' \
          --header 'X-API-Key: ${{ secrets.POSTMAN_API_KEY }}' \
          --data '@openapi/spec/postman-spec-in-collection-obj.json' \
          --fail

      # Files Generated during the intermediate steps of converting OpenAPI spec to body for Postman API are stored as artifacts
      # These files can be useful for debugging
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Generated Files
          path: openapi/spec
          retention-days: 10
